bug fix in urltopath
laosb/ghos3 pull request #8
Opened 2023-10-25 22:01 UTC by adityapatadia

`urlToPath` function should return actual path without the hostname field. This PR fixes it.

2023-10-25 22:02 UTC, adityapatadia commented
@laosb it would be great if you can merge and release this. Without this, files are stored in weird paths on S3.

2023-10-26 03:27 UTC, laosb commented
Looks good to me, I'll merge now on my phone, and release later.

This is a breaking change, though we are still in 0.x.

2023-10-26 03:32 UTC, laosb requested changes

2023-10-26 03:32 UTC, laosb commented on src/index.ts
> +    return parsedurl.pathname;
One nitpick though: `parsedurl` -> `parsedUrl`.

2023-10-26 04:59 UTC, adityapatadia commented
I have made the required change. Please check once if leading slash is fine or we need to remove it. I could not find any documentation on it.

2023-10-26 04:59 UTC, adityapatadia reviewed
Made changes.

2023-10-26 17:56 UTC, adityapatadia commented
Hi,
This is little bit urgent as our production uploads are stuck. Can you please merge and release. Apologies for the push.

2023-10-27 18:43 UTC, merged

2023-10-27 18:57 UTC, laosb commented
Published as 2.0.0 (with some type check fixes & deps bumped).

Thank you for doing a PR!